language: node_js
node_js:
  - 'node'


branches:
  only:
    - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

before_install:
- npm install -g npm@latest 
- npm install -g firebase-tools

install:
  - npm install
script:
- npm run clean && npm run build

after_script:
- firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: always
    on_success: change