language: ruby
os: osx
rvm:
- 2.3.3

branches:
  only:
    - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

before_script:
- gem install jekyll html-proofer
- npm install -g npm@latest 
- npm install -g firebase-tools

script:
- bundle exec jekyll build 

after_script:
- firebase hosting:disable
- firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: always
    on_success: change