language: node_js
node_js:
  - 'node'


branches:
  only:
    - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

before_install:
- npm install -g firebase-tools

script:
- npm run clean && npm run build

cache:
  directories:
    - "node_modules"

after_script:
- firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: always
    on_success: change